### PR TITLE
Add test actions

### PR DESCRIPTION
**Pull request by jhonpedro**
Add workflow for tests, don't know if this will be a check in the PR, hope yes

### CODE REVIEW

**Comment by jhonpedro** [comment]
Hehehe, worked

**Comment by jhonpedro** [comment]
2 checks

**Comment by jhonpedro** [comment]
We can make some interesting ones. Maybe we can take a look at big repos like [react](https://github.com/facebook/react) and see how they use their actions, I saw that they use CircleCI too, maybe it's a good thing to learn too!

**Review by henrfarias — APPROVED** [review]
Awesome!

**Pull request merged**
