### PR TITLE
8 remove the future value calculator

### PR DESCRIPTION
**Pull request by henrfarias**
I removed the future value calc and cover the date service, because we will need the all methods in another entities and without the future value calc method we would not have 100% coverage

### CODE REVIEW

**Comment by jhonpedro** [comment]
There is a check from GitGuardin, did you added this? If yes, how?

**Review by jhonpedro — APPROVED** [review]
Nice work!

**Comment by jhonpedro** [comment]
I forgot about the conflicts, just resolve them before the merge please :)

**Comment by henrfarias** [comment]
> 

It is a github trigger. I just assign the git guardian

**Pull request merged**
